'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import Header from '@/components/organisms/Header';
import Navigation from '@/components/organisms/Navigation';
import Footer from '@/components/organisms/Footer';
import SearchModal from '@/components/organisms/SearchModal';
import ArticleModal from '@/components/organisms/ArticleModal';
import SUNSTAR_DATA, { getArticleById } from '@/lib/data';

const TAB_LIST = [
  { id: 'daily', label: '📅 दैनिक' },
  { id: 'weekly', label: '🗓️ साप्ताहिक' },
  { id: 'monthly', label: '📆 मासिक' },
  { id: 'yearly', label: '🎆 वार्षिक (२०८३)' },
];

export default function RashifalPage() {
  const [activePeriod, setActivePeriod] = useState('daily');
  const [selectedSign, setSelectedSign] = useState<any>(null);
  const [rashifalList, setRashifalList] = useState<any[]>(SUNSTAR_DATA.rashifal || []);
  const [loading, setLoading] = useState(false);
  const [selectedArticle, setSelectedArticle] = useState<any>(null);
  const [isSearchOpen, setIsSearchOpen] = useState(false);

  useEffect(() => {
    let active = true;
    setLoading(true);

    fetch('/api/rashifal?type=' + activePeriod)
      .then((res) => res.json())
      .then((data) => {
        if (active && data && Array.isArray(data.predictions) && data.predictions.length > 0) {
          setRashifalList(data.predictions);
        }
      })
      .catch((err) => {
        console.error('Rashifal API error:', err);
      })
      .finally(() => {
        if (active) setLoading(false);
      });

    return () => {
      active = false;
    };
  }, [activePeriod]);

  const handleSelectArticle = (id: string) => {
    const found = getArticleById(id);
    if (found) {
      setSelectedArticle(found);
    }
  };

  const titleText =
    activePeriod === 'weekly'
      ? 'यो साताको साप्ताहिक राशिफल (Weekly Rashifal)'
      : activePeriod === 'monthly'
      ? 'यो महिनाको मासिक राशिफल (Monthly Rashifal)'
      : activePeriod === 'yearly'
      ? 'वर्ष २०८३ को वार्षिक राशिफल (Yearly Rashifal 2083)'
      : 'आजको दैनिक राशिफल (Daily Rashifal)';

  const subtitleText =
    activePeriod === 'weekly'
      ? 'यो साता व्यापार रोजगारी स्वास्थ्य र सम्बन्धमा कस्तो रहनेछ। साप्ताहिक विश्लेषण।'
      : activePeriod === 'monthly'
      ? 'यो महिना ग्रहको गोचर र नक्षत्र प्रभावले तपाईंको जीवनमा पार्ने असर र सम्भावना।'
      : activePeriod === 'yearly'
      ? 'नयाँ वर्ष २०८३ सालभरिको वृहत ग्रहगोचर व्यापार करियर र पारिवारिक भविष्यफल।'
      : 'आजको दिन तपाईंको ग्रह र नक्षत्र अनि भाग्यले के भन्दछ। १२ राशिको दैनिक भविष्यफल।';

  return (
    <div className="rashifal-page-shell">
      <Header onOpenSearch={() => setIsSearchOpen(true)} />
      <Navigation activeHref="/rashifal" />

      <main className="container" style={{ paddingTop: '24px', paddingBottom: '60px' }}>
        {/* Visual Banner generated by Nano Banana */}
        <div
          style={{
            borderRadius: '16px',
            overflow: 'hidden',
            marginBottom: '32px',
            boxShadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
            maxHeight: '340px',
            backgroundColor: '#0c1021',
          }}
        >
          <img
            src="/images/nepali_rashifal_banner.png"
            alt="Nepali Rashifal Astronomy Banner"
            style={{
              width: '100%',
              height: 'auto',
              maxHeight: '340px',
              objectFit: 'cover',
              display: 'block',
            }}
          />
        </div>

        {/* Title Header */}
        <div style={{ textAlign: 'center', marginBottom: '32px' }}>
          <span
            style={{
              backgroundColor: 'rgba(249, 115, 22, 0.1)',
              color: 'var(--brand-orange)',
              fontWeight: 800,
              fontSize: '0.85rem',
              padding: '6px 14px',
              borderRadius: '20px',
              display: 'inline-block',
              marginBottom: '10px',
            }}
          >
            🔮 सनस्टार ज्योतिष तथा भविष्यफल पोर्टल
          </span>
          <h1
            style={{
              fontSize: '2rem',
              fontWeight: 900,
              color: 'var(--text-primary)',
              marginBottom: '8px',
            }}
          >
            {titleText}
          </h1>
          <p style={{ fontSize: '1rem', color: 'var(--text-muted)', maxWidth: '680px', margin: '0 auto' }}>
            {subtitleText}
          </p>
        </div>

        {/* Timeframe Switcher Tabs */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            gap: '10px',
            flexWrap: 'wrap',
            marginBottom: '36px',
          }}
        >
          {TAB_LIST.map((tab) => {
            const isActive = activePeriod === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => {
                  setLoading(true);
                  setActivePeriod(tab.id);
                }}
                style={{
                  padding: '12px 24px',
                  borderRadius: '30px',
                  border: isActive ? '2px solid var(--brand-orange)' : '1px solid var(--border-color)',
                  backgroundColor: isActive ? 'var(--brand-orange)' : 'var(--bg-card)',
                  color: isActive ? '#ffffff' : 'var(--text-primary)',
                  fontWeight: 800,
                  fontSize: '0.95rem',
                  cursor: 'pointer',
                  boxShadow: isActive ? '0 4px 14px rgba(249, 115, 22, 0.3)' : 'var(--shadow-sm)',
                  transition: 'all 0.2s ease',
                }}
              >
                {tab.label}
              </button>
            );
          })}
        </div>

        {/* Cards Grid */}
        {loading ? (
          <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--text-muted)' }}>
            <span style={{ fontSize: '2rem', display: 'block', marginBottom: '10px' }}>🔮</span>
            <p style={{ fontWeight: 700 }}>राशिफल प्राप्त हुँदैछ, कृपया पर्खनुहोस्...</p>
          </div>
        ) : (
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
              gap: '20px',
            }}
          >
            {rashifalList.map((item, idx) => {
              const signName = item.sign || '';
              const latinStr = item.latinName || '';
              return (
                <div
                  key={item.id || signName || idx}
                  onClick={() => setSelectedSign(item)}
                  style={{
                    backgroundColor: 'var(--bg-card)',
                    border: '1px solid var(--border-color)',
                    borderRadius: 'var(--radius-lg)',
                    padding: '24px 20px',
                    cursor: 'pointer',
                    boxShadow: 'var(--shadow-sm)',
                    transition: 'transform 0.25s ease, box-shadow 0.25s ease, border-color 0.25s ease',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'space-between',
                  }}
                  className="rashifal-page-card"
                >
                  <div>
                    <div
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        marginBottom: '14px',
                      }}
                    >
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src={item.image || `/images/zodiac/${item.id}.png`}
                        alt={signName}
                        style={{ width: '58px', height: '58px', objectFit: 'contain' }}
                      />
                      <span
                        style={{
                          fontSize: '0.75rem',
                          fontWeight: 700,
                          color: 'var(--text-muted)',
                          backgroundColor: 'var(--bg-alt)',
                          padding: '3px 8px',
                          borderRadius: '12px',
                        }}
                      >
                        {item.dateRange || 'राशि फल'}
                      </span>
                    </div>

                    <h3 style={{ fontSize: '1.3rem', fontWeight: 900, color: 'var(--text-primary)', marginBottom: '2px' }}>
                      {signName} {latinStr}
                    </h3>

                    <div style={{ display: 'flex', gap: '8px', marginBottom: '14px', marginTop: '6px' }}>
                      {item.luckyColor && (
                        <span
                          style={{
                            fontSize: '0.75rem',
                            fontWeight: 700,
                            backgroundColor: 'rgba(249, 115, 22, 0.1)',
                            color: 'var(--brand-orange)',
                            padding: '2px 8px',
                            borderRadius: '4px',
                          }}
                        >
                          रंग: {item.luckyColor}
                        </span>
                      )}
                      {item.luckyNumber && (
                        <span
                          style={{
                            fontSize: '0.75rem',
                            fontWeight: 700,
                            backgroundColor: 'rgba(37, 99, 235, 0.1)',
                            color: 'var(--brand-blue)',
                            padding: '2px 8px',
                            borderRadius: '4px',
                          }}
                        >
                          अंक: {item.luckyNumber}
                        </span>
                      )}
                    </div>

                    <p
                      style={{
                        fontSize: '0.9rem',
                        lineHeight: 1.6,
                        color: 'var(--text-secondary)',
                        marginBottom: '16px',
                        display: '-webkit-box',
                        WebkitLineClamp: 4,
                        WebkitBoxOrient: 'vertical',
                        overflow: 'hidden',
                      }}
                    >
                      {item.prediction}
                    </p>
                  </div>

                  <div
                    style={{
                      paddingTop: '12px',
                      borderTop: '1px dashed var(--border-color)',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                    }}
                  >
                    <Link
                      href={`/rashifal/${item.id}`}
                      style={{ fontSize: '0.8rem', fontWeight: 800, color: 'var(--brand-blue)', textDecoration: 'none' }}
                      onClick={(e) => e.stopPropagation()}
                    >
                      विस्तृत राशिफल र प्रतिक्रिया ➔
                    </Link>
                    <span style={{ fontSize: '1.2rem' }}>🔮</span>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Modal Popup Viewer */}
        {selectedSign && (
          <div
            style={{
              position: 'fixed',
              inset: 0,
              backgroundColor: 'rgba(0, 0, 0, 0.75)',
              backdropFilter: 'blur(6px)',
              zIndex: 9999,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              padding: '20px',
            }}
            onClick={() => setSelectedSign(null)}
          >
            <div
              style={{
                backgroundColor: 'var(--bg-card)',
                borderRadius: 'var(--radius-lg)',
                padding: '32px',
                maxWidth: '540px',
                width: '100%',
                boxShadow: 'var(--shadow-lg)',
                border: '1px solid var(--border-color)',
              }}
              onClick={(e) => e.stopPropagation()}
            >
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  marginBottom: '20px',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                  <div style={{ width: '64px', height: '64px', borderRadius: '50%', flexShrink: 0, filter: 'drop-shadow(0 4px 8px rgba(0,0,0,0.25))' }}>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={selectedSign.image || `/images/zodiac/${selectedSign.id}.png`}
                      alt={selectedSign.sign}
                      style={{ width: '100%', height: '100%', objectFit: 'contain' }}
                    />
                  </div>
                  <div>
                    <h2 style={{ fontSize: '1.6rem', fontWeight: 900, color: 'var(--text-primary)' }}>
                      {selectedSign.sign} {selectedSign.latinName || ''}
                    </h2>
                    <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                      {selectedSign.dateRange}
                    </span>
                  </div>
                </div>
                <button
                  onClick={() => setSelectedSign(null)}
                  style={{
                    background: 'none',
                    border: 'none',
                    fontSize: '1.6rem',
                    cursor: 'pointer',
                    color: 'var(--text-muted)',
                  }}
                >
                  ✕
                </button>
              </div>

              <div
                style={{
                  display: 'flex',
                  gap: '14px',
                  marginBottom: '20px',
                  padding: '12px 16px',
                  backgroundColor: 'var(--bg-alt)',
                  borderRadius: '10px',
                }}
              >
                <span style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                  🎨 शुभ रंग: <strong>{selectedSign.luckyColor || 'उज्यालो रंग'}</strong>
                </span>
                <span style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                  🔢 शुभ अंक: <strong>{selectedSign.luckyNumber || '७'}</strong>
                </span>
              </div>

              <div style={{ marginBottom: '24px' }}>
                <h4 style={{ fontSize: '1rem', fontWeight: 900, color: 'var(--brand-orange)', marginBottom: '8px' }}>
                  {titleText}
                </h4>
                <p style={{ fontSize: '1rem', lineHeight: 1.65, color: 'var(--text-secondary)' }}>
                  {selectedSign.prediction}
                </p>
              </div>

              <div style={{ textAlign: 'right' }}>
                <button
                  onClick={() => setSelectedSign(null)}
                  style={{
                    padding: '10px 24px',
                    backgroundColor: 'var(--brand-blue)',
                    color: '#ffffff',
                    border: 'none',
                    borderRadius: '10px',
                    fontWeight: 800,
                    cursor: 'pointer',
                  }}
                >
                  बन्द गर्नुहोस्
                </button>
              </div>
            </div>
          </div>
        )}
      </main>

      <Footer onOpenSearch={() => setIsSearchOpen(true)} />

      <ArticleModal article={selectedArticle} onClose={() => setSelectedArticle(null)} />
      <SearchModal
        isOpen={isSearchOpen}
        onClose={() => setIsSearchOpen(false)}
        onSelectArticle={handleSelectArticle}
      />
    </div>
  );
}
